from dotenv import load_dotenv, find_dotenv
import os

load_dotenv(find_dotenv())

credentials =   {
        'CLIENT_ID' : os.getenv('CLIENT_ID'),
        'CLIENT_SECRET' : os.getenv('CLIENT_SECRET'),
        'NAME' : os.getenv('NAME'),
        'PASSWORD' : os.getenv('PASSWORD'),
        'USER_AGENT' : os.getenv('USER_AGENT'),
        'GROQ_API_KEY' : os.getenv('GROQ_API_KEY')
}

categories_mapping = {
'Administration & Leadership': 'topic/school-leadership',
'Arts': 'subject/arts',
'Arts Integration': 'topic/arts-integration',
'Assessment': 'assessment',
'Blended Learning': 'topic/blended-learning',
'Brain-Based Learning': 'topic/brain-based-learning',
'Bullying Prevention': 'topic/bullying-prevention',
'Career & Technical Education': 'topic/career-technical-education',
'ChatGPT & Generative AI': 'topic/chatgpt-generative-ai',
'Classroom Management': 'topic/classroom-management',
'Collaborative Learning': 'topic/collaborative-learning',
'College Readiness': 'topic/college-readiness',
'Communication Skills': 'topic/communication-skills',
'Community Partnerships': 'topic/community-partnerships',
'Computer Science/Coding': 'subject/computer-science-coding',
'Creativity': 'topic/creativity',
'Critical Thinking': 'topic/critical-thinking',
'Culturally Responsive Teaching': 'topic/culturally-responsive-teaching',
'Curriculum Planning': 'topic/curriculum-planning',
'Design Thinking': 'topic/design-thinking',
'Differentiated Instruction': 'topic/differentiated-instruction',
'Diversity': 'topic/diversity',
'Education Equity': 'topic/education-equity',
'Education Trends': 'topic/education-trends',
'English Language Arts': 'subject/english-language-arts',
'English Language Learners': 'topic/english-language-learners',
'Environmental Education': 'topic/environmental-education',
'Family Engagement': 'topic/family-engagement',
'Financial Literacy': 'topic/financial-literacy',
'Flexible Classrooms': 'topic/flexible-classrooms',
'Formative Assessment': 'topic/formative-assessment',
'Game-Based Learning': 'topic/game-based-learning',
'Homework': 'topic/homework',
'Inquiry-Based Learning': 'topic/inquiry-based-learning',
'Instructional Coaching': 'topic/instructional-coaching',
'Integrated Studies': 'integrated-studies',
'Interest-Based Learning': 'topic/interest-based-learning',
'Learning Environments': 'topic/learning-environments',
'Literacy': 'topic/literacy',
'Maker Education': 'topic/maker-education',
'Math': 'subject/math',
'Media Literacy': 'topic/media-literacy',
'Mental Health': 'topic/mental-health',
'Mindfulness': 'topic/mindfulness',
'New Teachers': 'topic/new-teachers',
'Online Learning': 'topic/online-learning',
'Parent Partnership': 'topic/parent-partnership',
'Physical Education': 'subject/physical-education',
'Place-Based Learning': 'topic/place-based-learning',
'Play & Recess': 'topic/play-recess',
'Professional Learning': 'topic/professional-learning',
'Project-Based Learning (PBL)': 'project-based-learning',
'Research': 'topic/research',
'Restorative Practices': 'topic/restorative-practices',
'School Culture': 'topic/school-culture',
'School Libraries': 'topic/school-libraries',
'Science': 'subject/science',
'Service Learning': 'topic/service-learning',
'Social & Emotional Learning (SEL)': 'social-emotional-learning',
'Social Studies/History': 'subject/social-studies',
'Special Education': 'topic/special-education',
'STEM': 'topic/stem',
'Student Engagement': 'topic/student-engagement',
'Student Voice': 'topic/student-voice',
'Student Wellness': 'topic/student-wellness',
'Teacher Collaboration': 'topic/teacher-collaboration',
'Teacher Wellness': 'topic/teacher-wellness',
'Teaching Strategies': 'topic/teaching-strategies',
'Technology Integration': 'technology-integration',
'Trauma-Informed Practices': 'topic/trauma-informed-practices',
'World Languages': 'subject/world-languages'}
